name: scalar-references-playwright
services:
  playwright:
    container_name: playwright-references
    ports:
      - 5001:5001
    network_mode: ${NETWORK:-bridge}
    init: true
    working_dir: /home/pwuser
    user: pwuser
    stop_signal: SIGINT
    stop_grace_period: 10s
    build: .
    command: /bin/sh -c "npx -y playwright@1.54.0 run-server --port 5001 --host
      0.0.0.0"
    environment:
      - NETWORK
