name: Auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      # Output github.event as json
      - name: Output github.event
        run: echo '${{ toJson(github.event) }}'
      # - name: Approve PR
      #   if: contains(github.event.pull_request.title, 'docs(contributor)')
      #   run: gh pr review --approve "$PR_URL"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GH_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      # - name: Enable auto-merge
      #   if: contains(github.event.pull_request.title, 'docs(contributor)')
      #   run: gh pr merge --auto --squash "$PR_URL"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GH_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
