name: Test Nuxt Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      - name: Build packages
        uses: ./.github/actions/build-blacksmith
        with:
          node-version: ${{ matrix.node-version }}
          packages: './packages/**'
      # Caching browser binaries is not recommended, since the amount of time it takes to restore the cache is comparable to the time it takes to download the binaries.
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Install Playwright dependencies
        run: npx playwright install-deps
      - name: Start nuxt server
        run: pnpm --filter nuxt dev --host &
      - name: Run e2e tests
        run: CI=1 pnpm -r --parallel test:e2e:nuxt
