name: Update Contributors in README

on:
  schedule:
    # Run every Friday at 15:00 UTC
    - cron: '0 15 * * 5'

jobs:
  update-readme:
    name: Update the README
    if: ${{ github.repository_owner == 'scalar' }}
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Update the list of contributors
        uses: akhilmhdh/contributors-readme-action@83ea0b4f1ac928fbfe88b9e8460a932a528eb79f # v2.3.11
        with:
          use_username: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
